using System.Diagnostics;
using HarmonyLib;
using UnityEngine;

namespace ValheimCommunityPatch.Patches.Performance {
    // Fix Arriving Location Hitch: a zone holding a location that has not been generated by the time
    // the host walks up to it is generated in the background first and then loaded the way
    // already-generated land loads, instead of being generated and built in full in one frame.
    //
    // The host pre-generates zones in a ring ahead of itself, in ghost mode, but only on ticks with
    // no nearby zone to load, so travelling briskly reaches zones nobody generated yet. PokeLocalZone
    // then spawns them in full: every networked object, the location's whole visual model and every
    // dungeon room model are built and kept in that frame, the largest single hitches of Deep North
    // travel. A zone generated in the background instead is loaded on arrival through the client
    // path, where the scene creates objects a few per frame, the location model waits for Fix
    // Location Spawn Hitch's budget, dungeon rooms are placed by Fix Dungeon Spawn Hitch's, and the
    // zone's contents wait for their room or location to finish, as on every client of a dedicated
    // server, which only ever loads new land that way.
    //
    // A prefix on PokeLocalZone, for an ungenerated zone that holds an unplaced location, runs
    // vanilla's ghost-mode SpawnZone in place of the full one, reports the tick as used, and charges
    // its time to the location and dungeon room budgets for the frame. The next tick's PokeLocalZone
    // finds the zone generated and loads it as vanilla does; the scene creates no nearby object while
    // a nearby zone is missing, so the background copies are gone before real ones exist, as for a
    // ghost-ring zone. The world, its saved objects and its dungeon layouts are the same as a
    // ghost-ring generation's; what moves is when the visible parts are built. Left to vanilla: the
    // player's own zone, behind a loading screen, zones without a location, and whenever another mod
    // can skip or rewrite PokeLocalZone or SpawnZone.
    //
    // Client: only a host with a local player loads zones around itself.
    [PatchSide(Side.Client)]
    [ModDisableable]
    [HarmonyPatch(typeof(ZoneSystem), "PokeLocalZone")]
    internal static class ArrivingZoneGhostPatch {
        private const string FixName = "Fix Arriving Location Hitch";

        private static readonly FixSwitch ApiSwitch = FixRegistry.SwitchOf(typeof(ArrivingZoneGhostPatch));

        private static readonly TakeoverCheck PokeTakeover = new TakeoverCheck(
            typeof(ArrivingZoneGhostPatch),
            AccessTools.DeclaredMethod(typeof(ZoneSystem), "PokeLocalZone"),
            transpilers: true,
            owners => $"Zone loading is changed by {owners}, so '{FixName}' stands down and arriving zones " +
                      "generate as that mod decides.");

        private static readonly TakeoverCheck SpawnTakeover = new TakeoverCheck(
            typeof(ArrivingZoneGhostPatch),
            AccessTools.DeclaredMethod(typeof(ZoneSystem), "SpawnZone"),
            transpilers: true,
            owners => $"Zone generation is changed by {owners}, so '{FixName}' stands down and arriving zones " +
                      "generate in full.");

        // Priority.Last: see ValheimCommunityPatch.ApplyPatches.
        [HarmonyPrefix]
        [HarmonyPriority(Priority.Last)]
        private static bool Prefix(ZoneSystem __instance, Vector2s zoneID, ref bool __result, bool __runOriginal) {
            if (!__runOriginal || ApiSwitch.Off || !GenerateFirst(__instance, zoneID, out string location)) { return true; }

            // Fails, as the full spawn would, while the terrain or the location prefab is still
            // loading; PokeLocalZone then reports nothing done, and the next tick asks again.
            long start = Stopwatch.GetTimestamp();
            __result = __instance.SpawnZone(zoneID, ZoneSystem.SpawnMode.Ghost, out GameObject _);

            // This frame's world-building budget is spent: location models and dungeon rooms already
            // waiting from earlier zones hold off until the next frame instead of piling on.
            long elapsed = Stopwatch.GetTimestamp() - start;
            LocationSpawnPacingPatch.ChargeFrame(elapsed);
            DungeonRoomSpreadPatch.ChargeFrame(elapsed);

            if (__result && Logger.DebugEnabled) {
                Logger.LogDebug($"{FixName}: zone {zoneID.x},{zoneID.y} with {location} generated in the background; it loads next tick.");
            }

            return false;
        }

        private static bool GenerateFirst(ZoneSystem zoneSystem, Vector2s zoneID, out string location) {
            location = null;

            ZNet znet = ZNet.instance;
            if (znet == null || !znet.IsServer() || Player.m_localPlayer == null || RunMode.InLoadingScreen()) { return false; }

            // Installed already (vanilla only refreshes it), or generated already (vanilla loads it).
            if (zoneSystem.m_zones.ContainsKey(zoneID) || zoneSystem.IsZoneGenerated(zoneID)) { return false; }

            if (!zoneSystem.m_locationInstances.TryGetValue(zoneID, out ZoneSystem.LocationInstance instance) || instance.m_placed) {
                return false;
            }

            // The ground under the player has to exist this tick.
            if (zoneID == ZoneSystem.GetZone(znet.GetReferencePosition())) { return false; }

            if (PokeTakeover.TakenOver || SpawnTakeover.TakenOver) { return false; }

            location = instance.m_location?.m_prefabName ?? "a location";
            return true;
        }
    }
}
