using System.Diagnostics;
using BepInEx.Configuration;
using HarmonyLib;
using UnityEngine;

namespace ValheimCommunityPatch.Patches.Performance {
    // Vanilla defect: ZoneSystem.Update generates one complete zone per 100 ms tick, entirely in
    // one frame - terrain mesh, collider cook, thousands of placement raycasts, hundreds of
    // instantiates - with no awareness of how the frame is doing. Walking into virgin terrain
    // means one full generation burst every 100 ms: exactly the "many micro stutters" signature,
    // and the dominant remaining spike source measured in live play.
    //
    // Most of those bursts are ghost zones: CreateGhostZones (ZoneSystem.cs:498) pre-generates
    // the wider ring around the host and each peer so the data exists before anyone arrives.
    // That work is preparation with no same-frame consumer - nothing stands in a ghost zone the
    // frame it generates (its objects are destroyed in the same call), and a zone a player
    // actually reaches is generated by CreateLocalZones, which this patch never touches.
    //
    // Two pacing signals, both feeding one per-frame skip decision:
    //
    //  - Frame pressure: when the previous frame already exceeded the budget, skip this tick.
    //    (At high framerates this alone rarely engages - the frame after a burst recovers long
    //    before the next 100 ms tick - which is why the second signal exists.)
    //
    //  - Generation cost: each ghost generation that runs is timed, and one that itself exceeded
    //    the budget arms a cooldown of N ticks. While exploring, that turns ten expensive bursts
    //    a second into roughly ten-over-(N+1) - the bursts are identical, just further apart.
    //
    // A starvation guard runs the generation regardless after a few consecutive skips, so a
    // machine that always exceeds the budget still pre-generates, just at a reduced rate. The
    // same zones generate in the same way from the same seeds - only *when* is paced. Callers
    // ignore the bool return, so returning false is transparent.
    //
    // Server: only the machine that owns the world reaches CreateGhostZones (vanilla gates it on
    // IsServer). On a dedicated server frames are simulation ticks (~20 ms); the default 30 ms
    // budget sits above that, so pacing only engages there when the server is genuinely
    // struggling - which is when deferring background generation helps most.
    [PatchSide(Side.Server)]
    [HarmonyPatch(typeof(ZoneSystem))]
    internal static class ZoneGenPacingPatch {
        internal static ConfigEntry<int> BudgetMs;
        internal static ConfigEntry<int> CooldownTicks;

        // After this many consecutive skipped ticks (0.1 s apart), generate regardless: bounds
        // the added latency for background generation to ~half a second under sustained load.
        private const int MaxConsecutiveSkips = 4;

        private static int _decisionFrame = -1;
        private static bool _skipThisFrame;
        private static int _consecutiveSkips;
        private static int _cooldownRemaining;

        internal static void BindConfig() {
            BudgetMs = ValConfig.BindServerConfig(
                ValConfig.SectionPerformance,
                "Zone Generation Frame Budget",
                30,
                "Milliseconds: a background zone generation tick is deferred when the previous " +
                "frame exceeded this, and a generation that itself took longer than this arms " +
                "the cooldown. Lower spreads generation out more aggressively.",
                advanced: true,
                valMin: 10,
                valMax: 100);

            CooldownTicks = ValConfig.BindServerConfig(
                ValConfig.SectionPerformance,
                "Zone Generation Cooldown Ticks",
                2,
                "How many 100ms ticks to wait after an expensive background zone generation " +
                "before the next one. 0 disables the cooldown and paces on frame pressure alone.",
                advanced: true,
                valMin: 0,
                valMax: 10);
        }

        [HarmonyPrefix]
        [HarmonyPatch("CreateGhostZones")]
        private static bool CreateGhostZonesPrefix(ref bool __result, out long __state) {
            __state = 0;

            // One decision per frame: Update calls this once for the host plus once per peer,
            // and they share it. Ticks are 100 ms apart, so each tick lands on its own frame.
            int frame = Time.frameCount;
            if (frame != _decisionFrame) {
                _decisionFrame = frame;

                float previousFrameMs = Time.unscaledDeltaTime * 1000f;
                int budget = BudgetMs != null ? BudgetMs.Value : 30;
                bool wantSkip = previousFrameMs > budget || _cooldownRemaining > 0;

                if (wantSkip && _consecutiveSkips < MaxConsecutiveSkips) {
                    _skipThisFrame = true;
                    _consecutiveSkips++;
                    if (_cooldownRemaining > 0) { _cooldownRemaining--; }
                } else {
                    _skipThisFrame = false;
                    _consecutiveSkips = 0;
                    // A guard-forced run also clears any cooldown remainder, so the guard does
                    // not immediately re-trip on the very next tick.
                    _cooldownRemaining = 0;
                }
            }

            if (_skipThisFrame) {
                __result = false;
                return false;
            }

            __state = Stopwatch.GetTimestamp();
            return true;
        }

        // Times the generations that ran. One that blew the frame budget on its own arms the
        // cooldown - the next ticks skip, spacing the bursts out.
        [HarmonyPostfix]
        [HarmonyPatch("CreateGhostZones")]
        private static void CreateGhostZonesPostfix(long __state) {
            if (__state == 0) { return; }
            if (CooldownTicks == null || CooldownTicks.Value <= 0) { return; }

            double elapsedMs = (Stopwatch.GetTimestamp() - __state) * 1000.0 / Stopwatch.Frequency;
            int budget = BudgetMs != null ? BudgetMs.Value : 30;

            if (elapsedMs > budget) { _cooldownRemaining = CooldownTicks.Value; }
        }
    }
}
